[package]
name = "tosql"
version = "0.1.0"
edition = "2021"
authors = ["Helly Guo <hellyguo@foxmail.com>"]
exclude = ["tests", "examples"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
simplelog = "0.10.2"
walkdir = "2.3.2"
regex = "1.5.4"
lazy_static = "1.4.0"
xml-rs = "0.8.4"
rstring-builder = "0.1.4"
